baseURL = "https://mousavi310.github.io/"
languageCode = "en-us"
title = "Morteza Mousavi"
theme = "chunky-poster"

[params]
  [params.prismJS]
    enable = true
    theme = "okaidia"


[menu]

  [[menu.main]]
    identifier = "about"
    name = "about me"
    pre = "<i class='fa fa-heart'></i>"
    url = "/about/"
    weight = -110
