baseURL = "https://mousavi310.github.io/"
languageCode = "en-us"
title = "Morteza Mousavi"
theme = "chunky-poster"

googleAnalytics = "UA-165926398-1"

[params]
  [params.prismJS]
    enable = true
    theme = "okaidia"


[menu]

  [[menu.main]]
    identifier = "aboutme"
    name = "About Me"
    pre = "<i class='fa fa-heart'></i>"
    url = "/aboutme/"
    weight = -110

